server:
  port: 8081

spring:
  application:
    name: pass-batch
  datasource:
    url: jdbc:mysql://localhost:3307/batch?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: boom
    password: boom
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
