server:
  port: 8081


spring:
  application:
    name: pass-batch
  datasource:
    url: jdbc:mysql://localhost:3307/batch?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: boom
    password: boom
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.type.descriptor.sql: off
