name: Java CI-CD - Develop and Release Branches

on:
  push:
    branches:
      - "release/*"  # release 브랜치에서의 push만을 대상으로 합니다.
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Harbor Registry
        run: docker login -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }} ${{ secrets.HARBOR_URL }}

      - name: Build and Push Docker image to Harbor Registry
        run: docker compose -f docker-compose.yml build webapp && docker compose -f docker-compose.yml push webapp
