name: Java CI-CD - Develop and Release Branches

on:
  push:
    branches:
      - "develop"
      - "release/*"  # release 브랜치에서의 push만을 대상으로 합니다.
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.5'

      - name: Build with Gradle Wrapper excluding test package
        run: |
          ./gradlew build -x test

      - name: Login to Harbor Registry
        run: docker login -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }} ${{ secrets.HARBOR_URL }}

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Set IMAGE_NAME variable
        run: |
          IMAGE_NAME=springboot_batch

      - name: Tag Docker image
        run: |
          IMAGE_NAME=springboot_batch
          docker tag myapp:latest reg-kdev.kollus.com/hyeongwoo/$IMAGE_NAME:${{ github.run_number }}
      

      - name: Push Docker image to Harbor Registry
        run: |
          docker push reg-kdev.kollus.com/hyeongwoo/$IMAGE_NAME:${{ github.run_number }}
