name: Java CI-CD - Feature Branches
on:
  push:
    branches:
      - feature
  pull_request:
    branches:
      - develop

jobs:
  sonarqube:
    name: sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew build sonarqube --info
