name: Java CI-CD - Feature Branches

on:
  push:
    branches:
      - "feature/*"  # feature 브랜치에서의 push만을 대상으로 합니다.
  pull_request:
    branches: [ "develop" ]

jobs:
  sonar-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/setup-gradle@v1
        with:
          gradle-version: '8.5'

      - name: generate application test report
        run: |
          ./gradlew test --parallel

      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./gradlew sonarqube -Dorg.gradle.jvmargs=-Xmx4g -Pversion=${GITHUB_SHA} --parallel
